# Generated by Django 3.0.2 on 2020-02-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
            ],
        ),
    ]
